/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import pane_selecionar.sel_funci;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pane_selecionar.criar_exame;
import pane_selecionar.sel_alunos;
import pane_selecionar.sel_salas;
import pane_selecionar.sel_vigi;
import projeto.*;


/**
 *  Esta Classe server para Criar um Exame e Adicionar à Lista de Exames.
 * @author Asus
 */
public class Add_Exame extends javax.swing.JInternalFrame {
    GridBagLayout layout = new GridBagLayout();
    sel_alunos selAlunos;
    sel_vigi selVigilantes;
    sel_funci selFuncionarios;
    sel_salas selSalas;
    criar_exame criaExame;
    
    private final ArrayList<Curso> cursos;
   
    private String epoca;
    
    private Exame novoExame;
    
    private ArrayList<Exame> exames;
    private ArrayList<Aluno> inscritos;
    private ArrayList<Docente> vigilantes;
    private ArrayList<NaoDocente> funcionarios;
    private ArrayList<Sala> salas;
    
    private Curso curso;
    /**
     * 
     * @param exames
     * @param cursos
     */
    public Add_Exame(ArrayList<Exame> exames, ArrayList<Curso> cursos) {
        initComponents();
        this.exames = exames;
        this.cursos = cursos;
        criaExame = new criar_exame(cursos);
        this.selAlunos = new sel_alunos(null, null);
        selVigilantes = new sel_vigi(null,null, null, 0.0);
        this.selFuncionarios = new sel_funci(null);
        this.selSalas = new sel_salas(null,null,null,0.0);
        
        jPanel_dinamico.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        
        jPanel_dinamico.add(selAlunos,c);
        jPanel_dinamico.add(criaExame,c);
        jPanel_dinamico.add(selVigilantes,c);
        jPanel_dinamico.add(selFuncionarios,c);
        jPanel_dinamico.add(selSalas,c);
        
        selAlunos.setVisible(false);
        selVigilantes.setVisible(false);
        selFuncionarios.setVisible(false);
        selSalas.setVisible(false);
        criaExame.setVisible(true); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel_cria = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel4 = new javax.swing.JLabel();
        jLabel_curso1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_curso1 = new javax.swing.JComboBox<>();
        jComboBox_disciplina1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jRadioButton_eEspecial = new javax.swing.JRadioButton();
        jRadioButton_eNormal = new javax.swing.JRadioButton();
        jRadioButton_eRecurso = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jButton_alunos = new javax.swing.JButton();
        jButton_funci = new javax.swing.JButton();
        jButton_vigi = new javax.swing.JButton();
        jButton_vali = new javax.swing.JButton();
        jButton_sSalas = new javax.swing.JButton();
        jPanel_dinamico = new javax.swing.JPanel();
        jLabel_curso = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel_criaLayout = new javax.swing.GroupLayout(jPanel_cria);
        jPanel_cria.setLayout(jPanel_criaLayout);
        jPanel_criaLayout.setHorizontalGroup(
            jPanel_criaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );
        jPanel_criaLayout.setVerticalGroup(
            jPanel_criaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        setClosable(true);
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Adicionar Exame");

        jInternalFrame1.setClosable(true);
        jInternalFrame1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jInternalFrame1formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Adicionar Exame");

        jLabel_curso1.setText("Curso");

        jLabel5.setText("Disciplina");

        jComboBox_curso1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha" }));
        jComboBox_curso1.setAutoscrolls(true);
        jComboBox_curso1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox_curso1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox_curso1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBox_curso1MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboBox_curso1MouseReleased(evt);
            }
        });

        jComboBox_disciplina1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha" }));
        jComboBox_disciplina1.setAutoscrolls(true);
        jComboBox_disciplina1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox_disciplina1MouseEntered(evt);
            }
        });

        jLabel6.setText("Data e hora:");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024" }));

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_curso1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_curso1)
                            .addComponent(jLabel5)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_disciplina1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel_curso1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox_curso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(11, 11, 11)
                .addComponent(jComboBox_disciplina1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGroup1.add(jRadioButton_eEspecial);
        jRadioButton_eEspecial.setText("Especial");

        buttonGroup1.add(jRadioButton_eNormal);
        jRadioButton_eNormal.setText("Normal");

        buttonGroup1.add(jRadioButton_eRecurso);
        jRadioButton_eRecurso.setText("Recurso");
        jRadioButton_eRecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_eRecursoActionPerformed(evt);
            }
        });

        jButton_alunos.setText("Alunos");
        jButton_alunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_alunosActionPerformed(evt);
            }
        });

        jButton_funci.setText("Funcionários");
        jButton_funci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_funciActionPerformed(evt);
            }
        });

        jButton_vigi.setText("Vigilantes");
        jButton_vigi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_vigiActionPerformed(evt);
            }
        });

        jButton_vali.setText("Validar");
        jButton_vali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_valiActionPerformed(evt);
            }
        });

        jButton_sSalas.setText("Salas");
        jButton_sSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sSalasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_funci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_alunos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_vigi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_vali)
                    .addComponent(jButton_sSalas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jButton_alunos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_vigi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_funci)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_sSalas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_vali)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_dinamicoLayout = new javax.swing.GroupLayout(jPanel_dinamico);
        jPanel_dinamico.setLayout(jPanel_dinamicoLayout);
        jPanel_dinamicoLayout.setHorizontalGroup(
            jPanel_dinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        jPanel_dinamicoLayout.setVerticalGroup(
            jPanel_dinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        jLabel_curso.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_dinamico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_curso)))
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jRadioButton_eNormal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton_eRecurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton_eEspecial))
            .addComponent(jLabel1)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 238, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 238, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButton_eNormal)
                    .addComponent(jRadioButton_eRecurso)
                    .addComponent(jRadioButton_eEspecial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel_dinamico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_curso)
                        .addGap(0, 35, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 191, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 191, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
       // jComboBox_curso.removeAllItems();
       //jComboBox_disciplina.removeAllItems();
    }//GEN-LAST:event_formAncestorAdded

    private void jComboBox_curso1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_curso1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_curso1MouseClicked

    private void jComboBox_curso1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_curso1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_curso1MouseEntered

    private void jComboBox_curso1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_curso1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_curso1MouseExited

    private void jComboBox_curso1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_curso1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_curso1MouseReleased

    private void jComboBox_disciplina1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_disciplina1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_disciplina1MouseEntered

    private void jInternalFrame1formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jInternalFrame1formAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jInternalFrame1formAncestorAdded

    private void jRadioButton_eRecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_eRecursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_eRecursoActionPerformed

    private void jButton_alunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_alunosActionPerformed
        // TODO add your handling code here:
        this.inscritos = new ArrayList<>();
        int ver = 0;
        if (jRadioButton_eNormal.isSelected()){
            this.epoca = "Normal";
            ver++;
        }
        if (jRadioButton_eEspecial.isSelected()){
            this.epoca = "Especial";
            ver++;
        }
        if (jRadioButton_eRecurso.isSelected()){
            this.epoca = "Recurso";
            ver++;
        }
        
        if (inscritos != null && ver!=0){
            for (Aluno alux : criaExame.getDisSel().get_Alunos()){
                if (epoca.equals("Especial") && (alux.getCurso().getDuracao()!=alux.getMatriculas()) && (alux.getRegime().equals("Normal") || alux.getRegime().equals("Erasmus"))){
                    
                }else
                    inscritos.add(alux);
            }
            this.selAlunos = new sel_alunos(inscritos,epoca);
            GridBagConstraints c = new GridBagConstraints();
            c.gridx = 0;
            c.gridy = 0;

            jPanel_dinamico.add(selAlunos,c);
               
            jRadioButton_eNormal.setVisible(false);
            jRadioButton_eRecurso.setVisible(false);
            jRadioButton_eEspecial.setVisible(false);
            selVigilantes.setVisible(false);
            selFuncionarios.setVisible(false);
            selSalas.setVisible(false);
            criaExame.setVisible(false);
            selAlunos.setVisible(true);
        }
    }//GEN-LAST:event_jButton_alunosActionPerformed

    private void jButton_valiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_valiActionPerformed
        // TODO add your handling code here:
        this.inscritos = new ArrayList<>();
        this.inscritos = selAlunos.getSelecionados();
        
        this.vigilantes = new ArrayList<>();
        this.vigilantes = selVigilantes.getSelecionados();
        
        this.funcionarios = new ArrayList<>();
        this.funcionarios = selFuncionarios.getSelecionados();
        
        this.salas = new ArrayList<>();
        this.salas = selSalas.getSalas_disponiveis();
        
        if( inscritos.size()>0 && vigilantes.size()>0 && funcionarios.size()>0 && salas.size()>0 ){
            double duracao = criaExame.getDuracao();        
            Disciplina dis = criaExame.getDisSel();
            Docente responsavel = criaExame.getDocente();
            Data data = criaExame.getData();


            if ("Especial".equals(epoca)){
                this.novoExame = new ExameEspecial(dis,data,duracao,salas,responsavel, vigilantes, funcionarios, inscritos, new ArrayList<>());
            }
            else{
                this.novoExame = new ExameNormalRecurso(dis,data,duracao,salas,responsavel, vigilantes, funcionarios, inscritos, new ArrayList<>(), epoca);
            }
            this.exames.add(novoExame);
            
            Ficheiros_obj obj = new Ficheiros_obj();     
            try {
                obj.write_exames(exames);
            } catch (IOException ex) {
                Logger.getLogger(Add_Exame.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Exame Adicionado com Sucesso!");
            setVisible(false);
        }
        else{
            jLabel_curso.setText("Opcões invalidas!");
        }
    }//GEN-LAST:event_jButton_valiActionPerformed

    private void jButton_vigiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_vigiActionPerformed
        // TODO add your handling code here:
        this.vigilantes = new ArrayList<>();
        if (jComboBox_curso1.getSelectedIndex()>=0){
            int inx = jComboBox_curso1.getSelectedIndex();
            Curso cs = cursos.get(inx);
            for (Disciplina dis : cs.getDisciplinas()) {
                for (Docente doc : dis.get_Docentes()) {
                    int v = 0;
                    for (Docente aux : vigilantes){
                        if (aux.getNum() == doc.getNum()) v++;
                    }
                    if (v == 0) vigilantes.add(doc);
                }
            }
            Data dt = criaExame.getData();
            double du = criaExame.getDuracao();

            selVigilantes = new sel_vigi(exames, vigilantes,dt,du);
            GridBagConstraints c = new GridBagConstraints();
            c.gridx = 0;
            c.gridy = 0;

            jPanel_dinamico.add(selVigilantes,c);

            selAlunos.setVisible(false);
            selVigilantes.setVisible(true);
            selFuncionarios.setVisible(false);
            selSalas.setVisible(false);
            criaExame.setVisible(false);
        }
    }//GEN-LAST:event_jButton_vigiActionPerformed

    private void jButton_funciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_funciActionPerformed
        // TODO add your handling code here:
        this.funcionarios = new ArrayList<>();
        Curso cs = criaExame.getCursoSel();
        
        if (cs != null){  
            this.funcionarios = cs.getFuncionarios();
            selFuncionarios = new sel_funci(funcionarios);
            GridBagConstraints c = new GridBagConstraints();
            c.gridx = 0;
            c.gridy = 0;

            jPanel_dinamico.add(selFuncionarios,c);

            selAlunos.setVisible(false);
            selVigilantes.setVisible(false);
            selFuncionarios.setVisible(true);
            criaExame.setVisible(false); 
            selSalas.setVisible(false); 
        }
    }//GEN-LAST:event_jButton_funciActionPerformed

    private void jButton_sSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sSalasActionPerformed
        // TODO add your handling code here:
        this.salas = new ArrayList<>();
        Curso cs = criaExame.getCursoSel();
        
        if (cs != null){ 
            this.salas = cs.getSalas();
            Data dt = criaExame.getData();
            double du = criaExame.getDuracao();
            selSalas = new sel_salas(salas, exames, dt, du);
            GridBagConstraints c = new GridBagConstraints();
            c.gridx = 0;
            c.gridy = 0;
            
            jPanel_dinamico.add(selSalas,c);
            
            selVigilantes.setVisible(false);
            selFuncionarios.setVisible(false);
            criaExame.setVisible(false);
            selAlunos.setVisible(false);
            selSalas.setVisible(true);
        }
    }//GEN-LAST:event_jButton_sSalasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton_alunos;
    private javax.swing.JButton jButton_funci;
    private javax.swing.JButton jButton_sSalas;
    private javax.swing.JButton jButton_vali;
    private javax.swing.JButton jButton_vigi;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox_curso1;
    private javax.swing.JComboBox<String> jComboBox_disciplina1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_curso;
    private javax.swing.JLabel jLabel_curso1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_cria;
    private javax.swing.JPanel jPanel_dinamico;
    private javax.swing.JRadioButton jRadioButton_eEspecial;
    private javax.swing.JRadioButton jRadioButton_eNormal;
    private javax.swing.JRadioButton jRadioButton_eRecurso;
    // End of variables declaration//GEN-END:variables
}
