/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import projeto.Curso;
import projeto.Disciplina;
import projeto.Docente;
import projeto.Ficheiros_obj;

/**
 * Esta Classe server para Criar uma novo Diciplina e Adicinoar à lista de Disciplinas de um Curso.
 * @author Asus
 */
public class Add_disciplina extends javax.swing.JInternalFrame {

    private String nomeCurso, nomeDisciplina;
    private int docenteResponsavel;
    private final ArrayList<Curso> cursos;
    private final ArrayList<Docente> doc;
    
    /**
     * 
     * @param cursos 
     */
    public Add_disciplina(ArrayList<Curso> cursos) {
        initComponents();
        this.cursos = cursos;
        this.doc = new ArrayList<>();
        this.doc.add(new Docente("Barros" , null, 101, null, null));
        this.doc.add(new Docente("Neves" , null, 102, null, null));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_disciplina = new javax.swing.JTextField();
        jButton_Adicionar = new javax.swing.JButton();
        jComboBox_docenter = new javax.swing.JComboBox<>();
        jComboBox_nomecurso = new javax.swing.JComboBox<>();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(610, 500));
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Adicionar Disciplina");

        jLabel2.setText("Nome do Curso");

        jLabel3.setText("Nome da Dsiciplina");

        jLabel4.setText("Nome do Docente Responsável ");

        jButton_Adicionar.setText("Adicionar");
        jButton_Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AdicionarActionPerformed(evt);
            }
        });

        jComboBox_docenter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "docentes" }));
        jComboBox_docenter.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jComboBox_docenterAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jComboBox_docenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_docenterActionPerformed(evt);
            }
        });

        jComboBox_nomecurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha" }));
        jComboBox_nomecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_nomecursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_disciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox_docenter, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_nomecurso, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Adicionar)
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox_nomecurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox_docenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_disciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jButton_Adicionar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AdicionarActionPerformed
        this.nomeCurso = jComboBox_nomecurso.getSelectedItem().toString();
        this.nomeDisciplina = jTextField_disciplina.getText();
        this.docenteResponsavel = jComboBox_docenter.getSelectedIndex();
        
        Disciplina novaDis = new Disciplina(nomeDisciplina , doc.get(docenteResponsavel) , doc , new ArrayList<>());
        for (Curso curso : cursos) {
            if (nomeCurso.equals(curso.getNome())){
                curso.getDisciplinas().add(novaDis);
                break;
            }    
        } 
        Ficheiros_obj obj = new Ficheiros_obj();     
        try {
            obj.write_cursos(cursos);
        } catch (IOException ex) {
            Logger.getLogger(Add_disciplina.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(false);
     
    }//GEN-LAST:event_jButton_AdicionarActionPerformed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
       jComboBox_nomecurso.removeAllItems();
    }//GEN-LAST:event_formAncestorAdded

    private void jComboBox_nomecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_nomecursoActionPerformed

        if (jComboBox_nomecurso.getItemCount()<1){
            for (int i = 0; i < cursos.size(); i++) {
                jComboBox_nomecurso.addItem(cursos.get(i).getNome());
            }
        }
    }//GEN-LAST:event_jComboBox_nomecursoActionPerformed

    private void jComboBox_docenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_docenterActionPerformed
        // TODO add your handling code here:
        if (jComboBox_docenter.getItemCount()<1){
            for (int i = 0; i < doc.size(); i++) {
                jComboBox_docenter.addItem(doc.get(i).getNome());
            }
        }
    }//GEN-LAST:event_jComboBox_docenterActionPerformed

    private void jComboBox_docenterAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jComboBox_docenterAncestorAdded
        // TODO add your handling code here:
        jComboBox_docenter.removeAllItems();
    }//GEN-LAST:event_jComboBox_docenterAncestorAdded

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Adicionar;
    private javax.swing.JComboBox<String> jComboBox_docenter;
    private javax.swing.JComboBox<String> jComboBox_nomecurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField_disciplina;
    // End of variables declaration//GEN-END:variables
}
