/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import projeto.Aluno;
import projeto.Curso;
import projeto.Disciplina;
import projeto.Ficheiros_obj;



/**
 * Esta Classe server para Criar um novo Aluno, associa-lo a um Curso e Disciplinas.
 * @author jcunha
 */
public class add_aluno extends javax.swing.JInternalFrame {

    /**
     * Creates new form add_aluno
     */
    private String nomeCurso, nome_aluno, regime, mail, nome_dis;
    private int num_matriculas;
    private long num_mac;
    private ArrayList<Disciplina> dis;
    private Curso temp;
    private final ArrayList<Curso> cursos;
    public add_aluno(ArrayList<Curso> cursos) {
        initComponents();
        this.cursos = cursos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlo = new javax.swing.JLabel();
        jLabel_curso = new javax.swing.JLabel();
        curso = new javax.swing.JComboBox<>();
        jLabel_nome = new javax.swing.JLabel();
        jText_nome = new javax.swing.JTextField();
        jLabel_regime = new javax.swing.JLabel();
        jCombo_regime = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jText_num = new javax.swing.JTextField();
        jLabelMatriculas = new javax.swing.JLabel();
        jCombo_matri = new javax.swing.JComboBox<>();
        adiciona = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jText_mail = new javax.swing.JTextField();
        jLabel_disciplina = new javax.swing.JLabel();
        jCombo_disci = new javax.swing.JComboBox<>();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(610, 500));

        titlo.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        titlo.setText("Adicionar Aluno");

        jLabel_curso.setText("Nome do curso");

        curso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        curso.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cursoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel_nome.setText("Nome do Aluno");

        jLabel_regime.setText("Regime");

        jCombo_regime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Trabalhador-Estudante", "Atleta", "Dirigente Associativo ", "Aluno de Erasmus" }));

        jLabel1.setText("Numero Mecanografico");

        jText_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_numActionPerformed(evt);
            }
        });

        jLabelMatriculas.setText("Matriculas");

        jCombo_matri.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        adiciona.setText("Adicionar");
        adiciona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                adicionaMousePressed(evt);
            }
        });
        adiciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionaActionPerformed(evt);
            }
        });

        jLabel2.setText("Mail");

        jLabel_disciplina.setText("Disciplina");

        jCombo_disci.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCombo_disci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCombo_disciMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMatriculas)
                    .addComponent(jText_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jText_num, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jText_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_nome)
                    .addComponent(jLabel_disciplina)
                    .addComponent(jLabel_curso)
                    .addComponent(titlo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCombo_disci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jCombo_matri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adiciona))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(197, 197, 197)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_regime)
                                .addComponent(jCombo_regime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_curso)
                    .addComponent(jLabel_regime))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCombo_regime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_disciplina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCombo_disci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jText_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jText_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jText_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMatriculas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCombo_matri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adiciona))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cursoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cursoAncestorAdded
        // TODO add your handling code here:
        curso.removeAllItems();
        jCombo_disci.removeAllItems();
        for (int i = 0; i < cursos.size(); i++) {
            curso.addItem(cursos.get(i).getNome());
        }
    }//GEN-LAST:event_cursoAncestorAdded

    private void adicionaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adicionaMousePressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_adicionaMousePressed

    private void jCombo_disciMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCombo_disciMousePressed
        // TODO add your handling code here:
        jCombo_disci.removeAllItems();
        this.nomeCurso = curso.getSelectedItem().toString();
        for(int i=0; i<cursos.size(); i++){
            if(nomeCurso.equals(cursos.get(i).getNome())){
                temp = cursos.get(i);             
                dis = temp.getDisciplinas();
                for(int j=0; j<dis.size(); j++){
                    jCombo_disci.addItem(dis.get(j).getNome());
                }
                break;
            }  
        }
    }//GEN-LAST:event_jCombo_disciMousePressed

    private void adicionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionaActionPerformed
        // TODO add your handling code here:
        this.nomeCurso = curso.getSelectedItem().toString();
        this.nome_dis = jCombo_disci.getSelectedItem().toString();
        this.nome_aluno = jText_nome.getText();
        this.num_matriculas = Integer.parseInt(jCombo_matri.getSelectedItem().toString());
        System.out.println(num_matriculas);
        this.regime = jCombo_regime.getSelectedItem().toString();
        this.num_mac = Long.parseLong(jText_num.getText());
        this.mail = jText_mail.getText();
        for(Curso cur:cursos){
            if(cur.getNome().equals(nomeCurso)){
                System.out.println(cur.toString());
                for(Disciplina dis: cur.getDisciplinas()){
                    if(dis.getNome().equals(nome_dis)){
                        System.out.println(dis.getNome());
                        Aluno novo = new Aluno(nome_aluno, mail, num_mac, num_matriculas, cur, regime);
                        dis.get_Alunos().add(novo);
                    }
                }
            }
        }
        setVisible(false);
        Ficheiros_obj obj = new Ficheiros_obj();     
        try {
            obj.write_cursos(cursos);
        } catch (IOException ex) {
            Logger.getLogger(add_aluno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_adicionaActionPerformed

    private void jText_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_numActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adiciona;
    private javax.swing.JComboBox<String> curso;
    private javax.swing.JComboBox<String> jCombo_disci;
    private javax.swing.JComboBox<String> jCombo_matri;
    private javax.swing.JComboBox<String> jCombo_regime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelMatriculas;
    private javax.swing.JLabel jLabel_curso;
    private javax.swing.JLabel jLabel_disciplina;
    private javax.swing.JLabel jLabel_nome;
    private javax.swing.JLabel jLabel_regime;
    private javax.swing.JTextField jText_mail;
    private javax.swing.JTextField jText_nome;
    private javax.swing.JTextField jText_num;
    private javax.swing.JLabel titlo;
    // End of variables declaration//GEN-END:variables
}
