/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import projeto.*;


/**
 * Esta Classe serve para Adicionar um ou mais Vigilantes a um Exame.
 * @author Asus
 */
public class Adiciona_Docentes_Exame extends javax.swing.JInternalFrame {

    /**
     * Creates new form Adiciona_Docentes_Exame
     */
    private final ArrayList<Curso> cursos;
    private final ArrayList<Exame> exames;
    private ArrayList<Docente> docentes;
    private int index;
    /**
     * 
     * @param exames
     * @param cursos 
     */
    public Adiciona_Docentes_Exame(ArrayList<Exame> exames, ArrayList<Curso> cursos) {
        initComponents();
        this.exames = exames;
        this.cursos = cursos;
        this.index = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox_Exames = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel_aviso = new javax.swing.JLabel();

        setClosable(true);
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel1.setText("Exames");

        jComboBox_Exames.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_Exames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ExamesActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Adicionar Docentes a um Exame");

        jLabel_aviso.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_Exames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_aviso)
                .addGap(77, 77, 77)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox_Exames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel_aviso))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_ExamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ExamesActionPerformed
        // TODO add your handling code here:
        if(jComboBox_Exames.getItemCount()<1){
            for(Exame ex:exames){
                jComboBox_Exames.addItem(ex.getDisciplina().getNome() + " (" + ex.getData().toString() + ")");
            }
        }
        else{
            if (jComboBox_Exames.getSelectedIndex()!= index){
                this.docentes = new ArrayList<>();
                this.index = jComboBox_Exames.getSelectedIndex();
                Exame selExame = exames.get(index);
                Data dt = selExame.getData();
                double du = selExame.getDuracao();
                for (Curso curso : cursos){
                    for (Disciplina dis : curso.getDisciplinas()) {
                        for (Docente doc : dis.get_Docentes()){
                            int v = 0;
                            for (Docente auxDoc : docentes){
                                if (doc.getNum() == auxDoc.getNum()) v++;
                            }
                            for (Docente auxVigi : selExame.getVigilantes()){
                                if (doc.getNum() == auxVigi.getNum()) v++;
                            }
                            if (v==0){
                                for (Exame exame : exames) {
                                    for (Docente aux : docentes) {
                                        if (doc.getNum() == aux.getNum()){
                                            if (Data.horaLivre(exame.getData(), exame.getDuracao(),dt,du)) v++;
                                        }
                                    }
                                }
                                if (v==0) docentes.add(doc);
                            }
                            
                        }
                    }
                }
                jList1.setModel(new javax.swing.AbstractListModel<String>() {

                    @Override
                    public int getSize() { return docentes.size(); }
                    @Override
                    public String getElementAt(int i) {

                        return docentes.get(i).getNome()+" Nº:"+ docentes.get(i).getNum(); }
                });
            }
        }
    }//GEN-LAST:event_jComboBox_ExamesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int[] indexs = jList1.getSelectedIndices();
        if(indexs.length > 0){
            for (int i = 0; i < indexs.length ; i++) {
                exames.get(index).getVigilantes().add(docentes.get(i));
            }
            setVisible(false);
             Ficheiros_obj obj = new Ficheiros_obj();     
            try {
                obj.write_exames(exames);
            } catch (IOException ex) {
                Logger.getLogger(Adiciona_Docentes_Exame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else jLabel_aviso.setText("Selecione algum aluno!");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
        jComboBox_Exames.removeAllItems();
    }//GEN-LAST:event_formAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox_Exames;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_aviso;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
