/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.util.ArrayList;
import projeto.*;

/**
 * Esta Classe serve para Listar os Exames contidos na Base de Dados.
 * @author Asus
 */
public class Listar_Exames extends javax.swing.JInternalFrame {
    
    
    /**
     * Creates new form Listar_Exames
     */
    private final ArrayList<Exame> exames;

    /**
     *
     * @param exames
     */
    public Listar_Exames(ArrayList<Exame> exames) {
        initComponents();
        this.exames = exames;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setClosable(true);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea1.setEnabled(false);
        jTextArea1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextArea1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextArea1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextArea1AncestorAdded
        // TODO add your handling code here:
        jTextArea1.append("Lista de Exames\n");
        for (Exame exame : exames) {
            jTextArea1.append("\nExame de "+exame.getDisciplina().getNome() + "\n");
            jTextArea1.append("Docente Responsável: "+exame.getDocente_responsavel().getNome()+"\t\tEpoca: "+exame.getTipo()+"\n");
            jTextArea1.append(exame.getData().toString());
           
            jTextArea1.append("Numero de Vigilantes: "+ exame.getVigilantes().size() + "\t\t");
            jTextArea1.append("Duração: " + exame.getDuracao() + "\n");
            
            jTextArea1.append("Número de Alunos: " + exame.getInscritos().size() + "\t\t");
            jTextArea1.append("salas: " + exame.getSalas().toString().replace("[", "").replace("]", "") + "\n");
        }
    }//GEN-LAST:event_jTextArea1AncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
