/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.util.ArrayList;
import javax.swing.JScrollPane;
import projeto.Aluno;
import projeto.Exame;

/**
 *  Esta Classe serve para Listar os Alunos Inscritos de um Exame.
 * @author jcunha
 */
public class Listar_Alunos_Incritos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Listar_Alunos_Incritos
     */
    private ArrayList<Exame> exames;
    private Exame exame_selct;
    private int index = -1;
    
    /**
     *
     * @param exames
     */
    public Listar_Alunos_Incritos(ArrayList<Exame> exames) {
        initComponents();
        this.exames = exames;   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel_disciplina = new javax.swing.JLabel();
        jCombo_dis = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setClosable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(610, 500));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Listar Alunos Inscritos");

        jLabel_disciplina.setText("Exame");

        jCombo_dis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCombo_dis.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jCombo_disAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jCombo_dis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombo_disActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea1.setEnabled(false);
        jTextArea1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextArea1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextArea1MouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_disciplina)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCombo_dis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(105, 387, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_disciplina)
                    .addComponent(jCombo_dis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextArea1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextArea1AncestorAdded
        // TODO add your handling code here:
        JScrollPane jS = new JScrollPane();
        jTextArea1.setText(null);
    }//GEN-LAST:event_jTextArea1AncestorAdded

    private void jCombo_disActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombo_disActionPerformed
        // TODO add your handling code here:
        if(jCombo_dis.getItemCount()<1){
            for(Exame ex:exames){
                jCombo_dis.addItem(ex.getDisciplina().getNome() + " (" + ex.getData().toString() + ")");
            }
        }
        else{
            if (jCombo_dis.getSelectedIndex()!= index){
                jTextArea1.setText(null);
                this.index = jCombo_dis.getSelectedIndex();
                this.exame_selct = exames.get(index);
                for(int i=0; i<exame_selct.getInscritos().size(); i++){
                    Aluno al = exame_selct.getInscritos().get(i);
                    if(exame_selct.getClassificacoes().size() != exame_selct.getInscritos().size()){
                        jTextArea1.append("\nNome: " + al.getNome() + "\nNúmero: " + al.getNum() + "\nClassificação: Não inserida\n");
                    }
                    else
                    {
                        jTextArea1.append("\nNome: " +al.getNome() + "\nNúmero: " +al.getNum()+ "\nClassificação: " + exame_selct.getClassificacoes().get(i).toString() + "\n");
                    }

                }
            }
        }
    }//GEN-LAST:event_jCombo_disActionPerformed

    private void jCombo_disAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jCombo_disAncestorAdded
        // TODO add your handling code here: 
        jCombo_dis.removeAllItems(); 
       
    }//GEN-LAST:event_jCombo_disAncestorAdded

    private void jTextArea1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea1MouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCombo_dis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_disciplina;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
