/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.util.ArrayList;
import javax.swing.JScrollPane;
import projeto.Curso;
import projeto.Disciplina;

/**
 * Esta Classe serve para Listar as Disciplinas de um Curso.
 * @author jcunha
 */
public class Listar_Disciplinas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Listar_Disciplinas
     */
    private int index;
    private String nomeCurso; 
    private ArrayList<Curso> cursos;

    /**
     *
     * @param cs
     */
    public Listar_Disciplinas(ArrayList<Curso> cs) {
        initComponents();
        this.cursos = cs;
        this.index = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jCombobox_cursos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(610, 500));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextArea1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextArea1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jCombobox_cursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCombobox_cursos.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jCombobox_cursosAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jCombobox_cursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCombobox_cursosMouseEntered(evt);
            }
        });
        jCombobox_cursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombobox_cursosActionPerformed(evt);
            }
        });

        jLabel1.setText("Curso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCombobox_cursos, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 419, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCombobox_cursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextArea1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextArea1AncestorAdded
        // TODO add your handling code here:
        JScrollPane jS = new JScrollPane();
        jTextArea1.setText(null);
    }//GEN-LAST:event_jTextArea1AncestorAdded

    private void jCombobox_cursosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jCombobox_cursosAncestorAdded
        // TODO add your handling code here:
        jCombobox_cursos.removeAllItems();
        jCombobox_cursos.removeAllItems();
        
    }//GEN-LAST:event_jCombobox_cursosAncestorAdded

    private void jCombobox_cursosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCombobox_cursosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jCombobox_cursosMouseEntered

    private void jCombobox_cursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombobox_cursosActionPerformed
        // TODO add your handling code here:
        if (jCombobox_cursos.getItemCount()<1){
            for (int i = 0; i < cursos.size(); i++) {
                jCombobox_cursos.addItem(cursos.get(i).getNome());
            }
        }
        else{
            if(jCombobox_cursos.getItemCount()!=index){
                this.index = jCombobox_cursos.getSelectedIndex();
                jTextArea1.setText(null);
                jTextArea1.append("Lista de Disciplinas\n");
                int v = 0;
                for (Disciplina dis : cursos.get(index).getDisciplinas()) {
                    jTextArea1.append("\n");
                    jTextArea1.append(dis.toString());
                    jTextArea1.append("\nNúmero de Alunos: "+dis.get_Alunos().size());
                    jTextArea1.append("\nNúmero de Docentes: "+dis.get_Docentes().size());
                    jTextArea1.append("\n");
                    v++;
                }
                if (v < 1){
                    jTextArea1.append("\nNao tem disciplinas\n"); 
                }
            }
        }
    }//GEN-LAST:event_jCombobox_cursosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCombobox_cursos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
