/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pane_selecionar;

import java.util.ArrayList;
import projeto.*;

/**
 * Esta Classe serve de auxilio da Classe Add_Exame, que atribui os Detalhes de um Novo Exame.
 * @author Asus
 */
public class criar_exame extends javax.swing.JPanel {

    
    private final ArrayList<Curso> cursos;
    private Curso curso;
    private Disciplina disciplina;
    private Docente docResponsavel;
    private Data dataExame;
    
    private double duracao;
    private int index_cs = -1;
    private int index_dis = -1;
    /**
     * 
     * @param cursos 
     */
    public criar_exame(ArrayList<Curso> cursos) {
        initComponents();
        this.cursos = cursos;
    }
    /**
     * 
     * @return 
     */
    public Data getData(){
        int d,m,a,h,min;
        d = Integer.parseInt(jComboBox_dia.getSelectedItem().toString());
        m = Integer.parseInt(jComboBox_mes.getSelectedItem().toString());
        a = Integer.parseInt(jComboBox_ano.getSelectedItem().toString());
        h = Integer.parseInt(jSpinner_horaI.getValue().toString());
        min = Integer.parseInt(jSpinner_minutoI.getValue().toString());
        this.dataExame = new Data(d,m,a,h,min);
        return this.dataExame;
    }
    /**
     * 
     * @return 
     */
    public Docente getDocente(){
        int index = jComboBox_docenteRes.getSelectedIndex();
        this.docResponsavel = disciplina.get_Docentes().get(index);
        return docResponsavel;
    }
    /**
     * 
     * @return 
     */
    public Curso getCursoSel(){
        int index = jComboBox_curso.getSelectedIndex();
        this.curso = cursos.get(index);
        return curso;
    }
    /**
     * 
     * @return 
     */
    public Disciplina getDisSel(){
        this.disciplina = new Disciplina("false",null,null,null);
        if (jComboBox_disciplina.getSelectedIndex()>=0){
            int index_d = jComboBox_disciplina.getSelectedIndex();
            int index_c = jComboBox_curso.getSelectedIndex();
            this.disciplina = cursos.get(index_c).getDisciplina(index_d);
        }
        return this.disciplina;
    }
    /**
     * 
     * @return 
     */
    public Double getDuracao(){
        int h,m;
        
        h = (Integer)jSpinner_horaF.getValue();
        m = (Integer)jSpinner_minutoF.getValue();

        this.duracao = h + 0.1*m;
        return this.duracao;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_curso = new javax.swing.JLabel();
        jComboBox_curso = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_disciplina = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox_dia = new javax.swing.JComboBox<>();
        jComboBox_mes = new javax.swing.JComboBox<>();
        jComboBox_ano = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jSpinner_horaI = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jSpinner_minutoI = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jSpinner_horaF = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jSpinner_minutoF = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_docenteRes = new javax.swing.JComboBox<>();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel_curso.setText("Curso");

        jComboBox_curso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha" }));
        jComboBox_curso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox_cursoMouseClicked(evt);
            }
        });
        jComboBox_curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_cursoActionPerformed(evt);
            }
        });

        jLabel2.setText("Disciplina");

        jComboBox_disciplina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha" }));
        jComboBox_disciplina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox_disciplinaMouseClicked(evt);
            }
        });
        jComboBox_disciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_disciplinaActionPerformed(evt);
            }
        });

        jLabel3.setText("Data:");

        jComboBox_dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBox_dia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox_diaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox_diaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBox_diaMouseExited(evt);
            }
        });

        jComboBox_mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jComboBox_mes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox_mesMouseClicked(evt);
            }
        });
        jComboBox_mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_mesActionPerformed(evt);
            }
        });

        jComboBox_ano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024" }));

        jLabel9.setText("Início:");

        jSpinner_horaI.setModel(new javax.swing.SpinnerNumberModel(8, 8, 18, 1));
        jSpinner_horaI.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel7.setText(":");

        jSpinner_minutoI.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabel10.setText("Duração:");

        jSpinner_horaF.setModel(new javax.swing.SpinnerNumberModel(0, 0, 3, 1));
        jSpinner_horaF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel11.setText(":");

        jSpinner_minutoF.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabel4.setText("Docente Responsável");

        jComboBox_docenteRes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha" }));
        jComboBox_docenteRes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox_docenteResMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_curso)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addComponent(jComboBox_docenteRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBox_curso, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox_disciplina, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 122, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jSpinner_horaI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner_minutoI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinner_horaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner_minutoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_curso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox_curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox_disciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jSpinner_horaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jSpinner_horaI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jSpinner_minutoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner_minutoI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox_docenteRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
        jComboBox_curso.removeAllItems();
        jComboBox_disciplina.removeAllItems();
        jComboBox_docenteRes.removeAllItems();
    }//GEN-LAST:event_formAncestorAdded

    private void jComboBox_cursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_cursoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox_cursoMouseClicked

    private void jComboBox_diaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_diaMouseClicked
        // TODO add your handling code here:      
    }//GEN-LAST:event_jComboBox_diaMouseClicked

    private void jComboBox_mesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_mesMouseClicked
        // TODO add your handling code here:        
    }//GEN-LAST:event_jComboBox_mesMouseClicked

    private void jComboBox_diaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_diaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_diaMouseExited

    private void jComboBox_diaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_diaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_diaMouseEntered

    private void jComboBox_docenteResMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_docenteResMouseClicked
        // TODO add your handling code here:   
    }//GEN-LAST:event_jComboBox_docenteResMouseClicked

    private void jComboBox_disciplinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_disciplinaMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox_disciplinaMouseClicked

    private void jComboBox_cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_cursoActionPerformed
        // TODO add your handling code here:
        if(jComboBox_curso.getItemCount()<1){
            for (int i = 0; i < cursos.size(); i++) {
                jComboBox_curso.addItem(cursos.get(i).getNome());
            }
        }
        else{
            if (jComboBox_curso.getSelectedIndex()!= index_cs){
                jComboBox_disciplina.removeAllItems();
                this.index_cs = jComboBox_curso.getSelectedIndex();
                    for (Disciplina dis : cursos.get(index_cs).getDisciplinas()) {
                        jComboBox_disciplina.addItem(dis.getNome());
                    }
                }
        }
    }//GEN-LAST:event_jComboBox_cursoActionPerformed

    private void jComboBox_disciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_disciplinaActionPerformed
        // TODO add your handling code here:
        if (jComboBox_disciplina.getSelectedIndex()!= index_dis){
            jComboBox_docenteRes.removeAllItems();
            this.index_dis = jComboBox_disciplina.getSelectedIndex();
            
            Disciplina auxDis = cursos.get(index_cs).getDisciplina(index_dis);
            for (Docente doc : auxDis.get_Docentes()) {
                jComboBox_docenteRes.addItem(doc.getNome() + " (" + doc.getNum() + ")");
            }
        }
    }//GEN-LAST:event_jComboBox_disciplinaActionPerformed

    private void jComboBox_mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_mesActionPerformed
        // TODO add your handling code here:
        jComboBox_dia.removeAllItems();
        switch (jComboBox_mes.getSelectedIndex()) {
            case 1:
                for (int i = 1; i < 29; i++) {
                    jComboBox_dia.addItem(String.valueOf(i));
                }   break;
            case 3:
            case 5:
            case 8:
            case 10:
                for (int i = 1; i < 31; i++) {
                    jComboBox_dia.addItem(String.valueOf(i));
                }   break;
            default:
                for (int i = 1; i < 32; i++) {
                    jComboBox_dia.addItem(String.valueOf(i));
                }   break;
        }
    }//GEN-LAST:event_jComboBox_mesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox_ano;
    private javax.swing.JComboBox<String> jComboBox_curso;
    private javax.swing.JComboBox<String> jComboBox_dia;
    private javax.swing.JComboBox<String> jComboBox_disciplina;
    private javax.swing.JComboBox<String> jComboBox_docenteRes;
    private javax.swing.JComboBox<String> jComboBox_mes;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_curso;
    private javax.swing.JSpinner jSpinner_horaF;
    private javax.swing.JSpinner jSpinner_horaI;
    private javax.swing.JSpinner jSpinner_minutoF;
    private javax.swing.JSpinner jSpinner_minutoI;
    // End of variables declaration//GEN-END:variables
}
